version: '3.8'
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ardeco
      MYSQL_ROOT_PASSWORD: mnw4xav-bud*eha*DCE
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - db_network

  db_test:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ardeco
      MYSQL_ROOT_PASSWORD: mnw4xav-bud*eha*DCE
    volumes:
      - dbdata_test:/var/lib/mysql
    ports:
      - "4406:3306"
    networks:
      - db_test_network

volumes:
  dbdata:
    external: true
  dbdata_test:
    external: true

networks:
  db_network:
    name: ardeco_db_network
    driver: bridge
  db_test_network:
    name: ardeco_db_test_network
    driver: bridge
