version: '3'
services:
  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ardeco
      MYSQL_ROOT_PASSWORD: mnw4xav-bud*eha*DCE
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"

  db_test:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ardeco
      MYSQL_ROOT_PASSWORD: mnw4xav-bud*eha*DCE
      MYSQL_TCP_PORT: 4406
    volumes:
      - dbdata_test:/var/lib/mysql
    ports:
      - "4406:4406"

volumes:
  dbdata:
    external: true
  dbdata_test:
    external: true
